[settings]
port = 8899

[[providers]]
name = "helius-devnet"
url = "https://devnet.helius-rpc.com/?api-key=ad0ff867-8155-4f12-b06a-e2b9cdb77447"
weight = 3

[[providers]]
name = "quicknode-devnet"
url = "https://burned-tame-shard.solana-devnet.quiknode.pro/86db8f093bde2218f105807430f68d55926f71bd/"
weight = 2

[[providers]]
name = "solana-devnet"
url = "https://api.devnet.solana.com"
weight = 1